### ISSUE TITLE
Cannot initialize on empty sequence.

### ISSUE THREAD

**Issue by birish2** [makinacorpus/django-geojson#77]
I have a geo object with no coordinates yet. When I try to read an empty geo, I thought it would return an empty geojson feature or no feature for that object, but i get the following stack trace:

Internal Server Error: /geodata
Traceback (most recent call last):
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/me/Desktop/projects/testproject/mysite/maptacs/views.py", line 53, in dispatch
    return super(GeoJSONLayerView, self).dispatch(*args, **kwargs)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/me/Desktop/projects/testproject/mysite/maptacs/views.py", line 87, in post
    **options)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/djgeojson/serializers.py", line 379, in serialize
    self.serialize_queryset(queryset)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/djgeojson/serializers.py", line 320, in serialize_queryset
    self.handle_field(obj, self.geometry_field)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/djgeojson/serializers.py", line 212, in handle_field
    value = getattr(obj, field_name)
  File "/home/me/Desktop/projects/testproject/mysite/maptacs/models.py", line 81, in geom
    return LineString(allpoints)
  File "/home/me/Desktop/projects/testproject/env/local/lib/python2.7/site-packages/django/contrib/gis/geos/linestring.py", line 42, in __init__
    raise TypeError('Cannot initialize on empty sequence.')
TypeError: Cannot initialize on empty sequence.

Looks like this is in the serializer.serialize function.

**Comment by birish2** [comment]
It was my error. I had built a custom geom property in my model that did not check for an empty array on the return.
