### ISSUE TITLE
'json.encoder' has no attribute 'FLOAT_REPR'

### ISSUE THREAD

**Issue by XavierCLL** [makinacorpus/django-geojson#80]
Using python 3.5

```
Internal Server Error: /data.geojson/2016-8-13/2016-8-14/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.5/site-packages/djgeojson/views.py", line 79, in dispatch
    return super(GeoJSONLayerView, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/generic/list.py", line 175, in get
    return self.render_to_response(context)
  File "/usr/local/lib/python3.5/site-packages/djgeojson/views.py", line 69, in render_to_response
    **options)
  File "/usr/local/lib/python3.5/site-packages/djgeojson/serializers.py", line 381, in serialize
    self.end_serialization()
  File "/usr/local/lib/python3.5/site-packages/djgeojson/serializers.py", line 162, in end_serialization
    floatrepr = json.encoder.FLOAT_REPR
AttributeError: module 'json.encoder' has no attribute 'FLOAT_REPR'
```

I tested replace the line 162 from serializers.py with that [from](http://stackoverflow.com/questions/1447287/format-floats-with-standard-json-module/1645929#1645929):
`floatrepr = lambda o: format(o, '.2f')`

and for me fix this error and work good, but need more test.

**Comment by W7PEA** [comment]
+1 I've hit this as well...

**Comment by cleder** [comment]
:+1: +1

**Comment by ad-m** [comment]
👍 +1

**Comment by chris10an** [comment]
+ 1
